# Prep

In [2]:
import pandas as pd

In [3]:
SILVER_FOLDER = r'C:\Users\User\Documents\GitHub\ap_workouts\silver_tables'

# Extract

In [7]:
df_workouts = pd.read_csv(f"{SILVER_FOLDER}/workouts.csv", sep=";", decimal=',')
df_exercises_log = pd.read_csv(f"{SILVER_FOLDER}/exercises_log.csv", sep=";", decimal=',')

In [10]:
df_exercises_log.query(" exercise_name == 'Leg Press' ")

,workout_id,exercise_number,exercise_name,equipment,reps_goal,set_number,weigth,quantity,measure,comments
0,202408231913,1,Leg Press,Machine,12 reps,1,206,12,reps,[]
1,202408231913,1,Leg Press,Machine,12 reps,2,206,12,reps,[]
2,202408231913,1,Leg Press,Machine,12 reps,3,210,15,reps,[]
51,202408161902,1,Leg Press,Machine,10 reps,1,200,12,reps,[]
52,202408161902,1,Leg Press,Machine,10 reps,2,200,12,reps,[]
...,...,...,...,...,...,...,...,...,...,...
2601,202310191445,1,Leg Press,Machine,12 reps,2,144,12,reps,[]
2602,202310191445,1,Leg Press,Machine,12 reps,3,144,12,reps,[]
2654,20231014949,1,Leg Press,Machine,12 reps,1,136,15,reps,[]
2655,20231014949,1,Leg Press,Machine,12 reps,2,140,12,reps,[]
2656,20231014949,1,Leg Press,Machine,12 reps,3,140,12,reps,[]